# https://hub.docker.com/r/itzg/minecraft-bedrock-server
version: "3.9"
services:
  mc-bedrock:
    image: "itzg/minecraft-bedrock-server"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Tropinha Server"
      GAMEMODE: survival
      DIFFICULTY: normal
      VIEW_DISTANCE: 16
      # https://minecraft.fandom.com/wiki/Server.properties#Bedrock_Edition_3
      # SERVER_PORT:
      # SERVER_PORT_V6:
      # GAMEMODE:
      # DIFFICULTY:
      # LEVEL_TYPE:
      # ALLOW_CHEATS:
      # MAX_PLAYERS:
      # ONLINE_MODE:
      # WHITE_LIST:
      # TICK_DISTANCE:
      # PLAYER_IDLE_TIMEOUT:
      # MAX_THREADS:
      # LEVEL_NAME:
      # LEVEL_SEED:
      # DEFAULT_PLAYER_PERMISSION_LEVEL:
      # TEXTUREPACK_REQUIRED:
      # SERVER_AUTHORITATIVE_MOVEMENT:
      # PLAYER_MOVEMENT_SCORE_THRESHOLD:
      # PLAYER_MOVEMENT_DISTANCE_THRESHOLD:
      # PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS:
      # CORRECT_PLAYER_MOVEMENT:
    ports:
      - "19132:19132/udp"
    volumes:
      - mc-volume:/data
      - ./data:/data
volumes:
  mc-volume:
    external: true
